FROM ubuntu:16.04

RUN apt-get update && apt-get install -y doxygen graphviz

COPY doc /fittexxcoin-node/doc
COPY src /fittexxcoin-node/src

WORKDIR /fittexxcoin-node

RUN doxygen doc/Doxyfile

FROM nginx:alpine

COPY --from=0 /fittexxcoin-node/doc/doxygen/html /usr/share/nginx/html
