#pragma once
/**
 * List of fixed seed nodes for the Fittexxcoin main and test networks
 * @generated by contrib/seeds/generate-seeds.py
 *
 * Each string must be numeric IPv4 dot-notation or numeric
 * IPv6 hex notation, followed by a colon and a port.
 */
static const SeedSpec6 pnSeed6_main[] = {
    { "164.68.126.156:7890" }
};

static const SeedSpec6 pnSeed6_testnet3[] = {
    { "154.251.81.112:17890" },
    { "154.240.0.0:17890" }
};

static const SeedSpec6 pnSeed6_testnet4[] = {
    { "154.251.81.112:27890" },
    { "154.240.0.0:27890" }
};

static const SeedSpec6 pnSeed6_scalenet[] = {
    { "154.251.81.112:37890" },
    { "154.240.0.0:37890" }
};

static const SeedSpec6 pnSeed6_chipnet[] = {
    { "154.251.81.112:47890" },
    { "154.240.0.0:47890" }
};
